#! /bin/bash
IFS=$'\t'
set -eo pipefail

TASK='connect'
NAME=''
AWS_REGION=${AWS_REGION}

info() {
  echo -e "\033[0;32m$1\033[0m"
}

warn() {
  echo -e "\033[0;93m$1\033[0m"
}

error() {

  echo -e "\033[0;91m$1\033[0m" >&2
}

function usage() {
  local SELF=`basename $0`
  cat <<EOF
Usage: $SELF [options] [<ClusterName>]

Options:
  --region                    : Set the AWS region
  -h, --help                  : Show this message
EOF
}

function no_eks_cluster_found() {
  if [ "${AWS_REGION}" == "" ]; then
    error "[Not Found] EKS Cluster"
  else
    error "[Not Found] EKS Cluster in region ${AWS_REGION}"
  fi
  warn "[Available] EKS Cluster running"
  list_available_eks_clsuter
}

function list_available_eks_clsuter() {
  local region_opt
  if [[ ${AWS_REGION} != '' ]]; then
    region_opt="--region ${AWS_REGION}"
  fi
  eval "aws ${region_opt} cloudformation list-stacks --stack-status-filter CREATE_COMPLETE" | grep StackName | grep -e 'eks-.*-cdk-stack"' | sed 's/.*: "\(.*\)",/\1/'
}

function verifyCfStackName() {
  IFS=$'\t\n'
  local name=$1
  local stackName

  if command -v cdk > /dev/null && [[ $name == '' ]]; then
    name=$(cdk context -j | grep '"name":' | awk '{print $2}' | sed 's/"\(.*\)",/\1/g' || '')
  fi

  if [[ $name =~ eks-.*-cdk-stack$ ]]; then
    stackName=$name
  else
    stackName="eks-$name-cdk-stack"
  fi

  for i in $(list_available_eks_clsuter)
  do
    if [[ $i == $stackName ]]; then
      echo $stackName
      return 0
    fi
  done

  return 1
}


function replace_domain() {
  local primehub_domain=$1
  local elb_domain=${2:-}

  local extension=''
  if [[ "$(uname)" == "Darwin" ]]; then
    extension=".bak"
  fi

  info "[Patch] ELB Domain -> ${primehub_domain}"
  k8s_context=$(kubectl config current-context)
  if [ "${elb_domain}" != '' ]; then
    sed -i ${extension} "s/customHostname: \${Token.*}/customHostname: ${elb_domain}/g" ~/.primehub/config/${k8s_context}/helm_override/primehub.yaml
  fi
  sed -i ${extension} "s/\${Token.*}/${primehub_domain}/g" ~/.primehub/config/${k8s_context}/.env
  sed -i ${extension} "s/\${Token.*}/${primehub_domain}/g" ~/.primehub/config/${k8s_context}/helm_override/primehub.yaml
}

function connect() {
  IFS=$'\t'
  local stackName=$1

  if command -v cdk > /dev/null && [ "${AWS_REGION}" == "" ]; then
    AWS_REGION=$(cdk context -j | grep '"region":' | awk '{print $2}' | sed 's/"\(.*\)",/\1/g' || echo "")
  fi

  if [ "${AWS_REGION}" != "" ]; then
    cf_output=$(aws cloudformation describe-stacks --stack-name ${stackName} --region ${AWS_REGION} --query "Stacks[0].Outputs[*]" --output text)
  else
    cf_output=$(aws cloudformation describe-stacks --stack-name ${stackName} --query "Stacks[0].Outputs[*]" --output text)
  fi

  cluster_name=$(echo ${cf_output} | grep ^ClusterClusterName | awk '{print $2}')
  k8s_context_cmd="$(echo ${cf_output} | grep ^ClusterConfigCommand | awk '{$1 = ""; print $0;}') --alias $cluster_name"
  config_bucket=$(echo ${cf_output} | grep ^PrimeHubConfigS3Bucket | awk '{$1 = ""; print $0;}' | sed 's/ //g')

  info "[Connect] EKS Cluster ${cluster_name}"
  eval "$k8s_context_cmd"

  info "[Fetch] PrimeHub Config from S3 bucket ${config_bucket}"
  k8s_context=$(kubectl config current-context)
  mkdir -p ~/.primehub/config/${k8s_context}/helm_override
  aws s3 cp s3://${config_bucket}/.env ~/.primehub/config/${k8s_context}/
  aws s3 cp s3://${config_bucket}/helm_override/primehub.yaml ~/.primehub/config/${k8s_context}/helm_override/

  info "[PrimeHub] Config"
  AWS_ELB_DOMAIN=$(echo ${cf_output} | grep ^AWSELBDomain | awk '{$1 = ""; print $0;}' | sed 's/ //g')
  AWS_CLOUDFRONT_DOMAIN=$(echo ${cf_output} | grep ^AWSCloudFrontDomain | awk '{$1 = ""; print $0;}' | sed 's/ //g')
  PRIMEHUB_URL=$(echo ${cf_output} | grep ^PrimeHubURL | awk '{$1 = ""; print $0;}' | sed 's/ //g')
  KC_URL="${PRIMEHUB_URL}/auth"
  PH_USER=$(echo ${cf_output} | grep ^PrimeHubAccount | awk '{$1 = ""; print $0;}' | sed 's/ //g')
  PH_PASSWORD=$(echo ${cf_output} | grep ^PrimeHubPassword | awk '{$1 = ""; print $0;}' | sed 's/ //g')
  KC_USER=$(echo ${cf_output} | grep ^KeycloakAccount | awk '{$1 = ""; print $0;}' | sed 's/ //g')
  KC_PASSWORD=$(echo ${cf_output} | grep ^KeycloakPassword | awk '{$1 = ""; print $0;}' | sed 's/ //g')

  echo ""
  echo "  AWS ELB Domain: ${AWS_ELB_DOMAIN}"
  echo "  PrimeHub:       ${PRIMEHUB_URL}  ( ${PH_USER} / ${PH_PASSWORD} )"
  echo "  Id Server:      ${KC_URL}/admin/ ( ${KC_USER} / ${KC_PASSWORD} )"
  echo ""

  if [ "${PRIMEHUB_URL}" == "https://${AWS_ELB_DOMAIN}" ]; then
    replace_domain ${AWS_ELB_DOMAIN}
  elif [ "${PRIMEHUB_URL}" == "https://${AWS_CLOUDFRONT_DOMAIN}" ]; then
    replace_domain ${AWS_CLOUDFRONT_DOMAIN} ${AWS_ELB_DOMAIN}
  fi
}

function main() {
  while (( "$#" )); do
    case "${1:-}" in
      --list)
        TASK='list'
      ;;
      --region)
        shift
        AWS_REGION=${1}
      ;;
      -h|--help)
        usage
        exit 0
      ;;
      *)
        if [ "${NAME}" == "" ]; then
          NAME=$1
        else
          error "[Syntax error] Should only provide one cluster name"
          usage
          exit 1
        fi
      ;;
    esac
    shift || (usage; exit 1)
  done

  if ! command -v kubectl > /dev/null; then
    error '[Error] No kubectl installed'
    echo '  Please install kubectl'
  fi
  if ! command -v aws > /dev/null; then
    error '[Error] No awscli installed'
    echo '  Please install awscli'
  fi

  if [ "${TASK}" == 'list' ]; then
    info "[Available] EKS Cluster"
    list_available_eks_clsuter
  else
    stackName=$(verifyCfStackName $NAME) || (no_eks_cluster_found; exit 1)
    connect $stackName
  fi
}

main "$@"
