#! /bin/bash
set -eo pipefail

NAME=
DRY_MODE=false
PRIMEHUB_MODE=ee
PRIMEHUB_VERSION=''
K8S_INFRA_ONLY=false
ENFORCE_UPDATE_PASSWORD=false
AWS_ACCOUNT=${AWS_ACCOUNT:-}
AWS_REGION=${AWS_REGION:-$(aws configure get region || echo 'ap-northeast-1')}
AWS_ZONE=${AWS_ZONE:-a}
CPU_INSTANCE='t3a.xlarge'
GPU_INSTANCE='g4dn.xlarge'
CPU_DESIRED_SIZE=0
GPU_DESIRED_SIZE=0
CPU_MAX_SIZE=2
GPU_MAX_SIZE=2
SCALE_DWON_DELAY=10
SYS_INSTANCE='t3a.xlarge'
PH_PASSWORD=''
KC_PASSWORD=''
PH_USER_EMAIL=''

info() {
  echo -e "\033[0;32m$1\033[0m"
}

warn() {
  echo -e "\033[0;93m$1\033[0m"
}

error() {
  echo -e "\033[0;91m$1\033[0m" >&2
}

usage() {
  local SELF=`basename $0`
  cat <<EOF
Usage: $SELF [options] <ClusterName>

Options:
  --mode                  <mode>              : Set the PrimeHub mode           ( Default: ${PRIMEHUB_MODE}, Support: ee, ce, deploy )
  --region                <aws region>        : Set the AWS region              ( Default: ${AWS_REGION} )
  --zone                  <zone>              : Set the AWS availability zones  ( Default: ${AWS_ZONE} )
  --dry-run                                   : Dry run AWS CDK deploy
  --k8s-infra                                 : Only setup AWS ESK without installing PrimeHub
  --enforce-update-password                   : Enforce default user reset password after first login
  --domain                <base domain>       : Provide the base domain managed by AWS Route 53
  --email                 <email>             : Set the email of default user
  --primehub-version      <version>           : Set the specific version number of PrimeHub
  --system-instance-type  <ec2 instance type> : Set the EKS default system node group instance type ( Default: ${SYS_INSTANCE} )
  --cpu-instance-type     <ec2 instance type> : Set the EKS default CPU node group instance type    ( Default: ${CPU_INSTANCE} )
  --gpu-instance-type     <ec2 instance type> : Set the EKS default GPU node group instance type    ( Default: ${GPU_INSTANCE} )
  --cpu-desired-capacity  <number>            : Set the EKS default CPU node group desired capacity ( Default: 0 )
  --gpu-desired-capactiy  <number>            : Set the EKS default GPU node group desired capacity ( Default: 0 )
  --cpu-max-capacity      <number>            : Set the EKS default CPU node group max capacity     ( Default: 2 )
  --gpu-max-capactiy      <number>            : Set the EKS default GPU node group max capacity     ( Default: 2 )
  --scale-down-delay      <number>            : Set the EKS autoscale scale down delay in minutes   ( Default: 10 )
  --keycloak-password     <password>          : Set the password of Keycloak admin account
  --primehub-password     <password>          : Set the password of PrimeHub default account
  -h, --help                                  : Show this message
EOF
}

node::version() {
  info "[Node] Version"
  node -v
}

node::packages() {
  info "\n[Fetch] Packages"
  yarn install
  echo ""
}

cdk::context() {
  if aws sts get-caller-identity | grep "Arn" | grep "assumed-role"; then
    export USERNAME=$(aws sts get-caller-identity  | grep "Arn" | sed 's/.*:assumed-role\/\(.*\)\/.*/\1/')
  else
    export USERNAME=$(aws iam get-user | jq ".User.UserName" | sed -e 's/"//g')
  fi
  export NAME=${NAME:-'cdk'}
  export AWS_ACCOUNT=$(aws sts get-caller-identity | grep "Account" | sed 's/.*Account": "\(.*\)",/\1/' | sed 's/ //g')

  if [ -f "./cdk.context.json" ]; then
    warn "[Detect] The CDK context already exist. Backup it by cdk.context.bak"
    mv cdk.context.json cdk.context.bak
  fi

  if [ ! -f "./cdk.context.json" ] || ! (cat ./cdk.context.json | grep '"clusterType": "dev-eks"' > /dev/null ); then
    info "[Create] CDK context"
    AWS_BASED_DOMAIN=${AWS_BASED_DOMAIN:-''}
    PRIMEHUB_VERSION=${PRIMEHUB_VERSION:-''}
    PH_PASSWORD=${PH_PASSWORD:-"$(openssl rand -hex 16)"}
    KC_PASSWORD=${KC_PASSWORD:-"$(openssl rand -hex 16)"}
    ADMIN_UI_GRAPHQL_SECRET_KEY=$(openssl rand -hex 32)
    HUB_PROXY_SECRET_TOKEN=$(openssl rand -hex 32)

    cdk context \
      -c clusterType=dev-eks \
      -c username=$USERNAME \
      -c name=$NAME \
      -c region=$AWS_REGION \
      -c zone=$AWS_ZONE \
      -c email=$PH_USER_EMAIL \
      -c primehubVersion=$PRIMEHUB_VERSION \
      -c cpuInstance=$CPU_INSTANCE \
      -c gpuInstance=$GPU_INSTANCE \
      -c cpuDesiredCapacity=$CPU_DESIRED_SIZE \
      -c gpuDesiredCapacity=$GPU_DESIRED_SIZE \
      -c cpuMaxCapacity=$CPU_MAX_SIZE \
      -c gpuMaxCapacity=$GPU_MAX_SIZE \
      -c scaleDownDelay=$SCALE_DWON_DELAY \
      -c systemInstance=$SYS_INSTANCE \
      -c basedDomain=$AWS_BASED_DOMAIN \
      -c primehubMode=$PRIMEHUB_MODE \
      -c primehubPassword=$PH_PASSWORD \
      -c keycloakPassword=$KC_PASSWORD \
      -c GraphqlSecretKey=$ADMIN_UI_GRAPHQL_SECRET_KEY \
      -c HubProxySecretKey=$HUB_PROXY_SECRET_TOKEN \
      -c k8sInfraOnly=$K8S_INFRA_ONLY \
      -c enforceUpdatePassword=$ENFORCE_UPDATE_PASSWORD \
      --json --strict > cdk.context.tmp
      mv cdk.context.tmp cdk.context.json
      cdk context
  else
    info "[Found] CDK context"
    cdk context
  fi
}

cdk::deploy() {
  info "[Bootstrap] aws://${AWS_ACCOUNT}/${AWS_REGION}"
  cdk bootstrap aws://${AWS_ACCOUNT}/${AWS_REGION}

  info "[Deploy] eks-$NAME by $USERNAME"
  cdk deploy
}

cdk::dry() {
  info "[Dry Run] eks-$NAME by $USERNAME"
  cdk synth > cdk.cloudformation.out
  info "[Output] Please check the output from 'cdk.cloudformation.out'"
}

args::parse() {
  while (( "$#" )); do
    case "${1:-}" in
      --mode)
        shift
        if [[ "${1}" != 'ee' && "${1}" != 'ce' && "${1}" != 'deploy' ]]; then
          error "[Not Support] PrimeHub Mode '${1}' not support"
          usage
          exit 2
        fi
        PRIMEHUB_MODE=${1}
        ;;
      --region)
        shift
        AWS_REGION=${1}
      ;;
      --zone)
        shift
        AWS_ZONE=${1}
      ;;
      --email)
        shift
        PH_USER_EMAIL=${1}
      ;;
      --primehub-version)
        shift
        PRIMEHUB_VERSION=${1}
      ;;
      --cpu-instance-type)
        shift
        CPU_INSTANCE=${1}
      ;;
      --gpu-instance-type)
        shift
        GPU_INSTANCE=${1}
      ;;
      --system-instance-type)
        shift
        SYS_INSTANCE=${1}
      ;;
      --cpu-desired-capacity)
        shift
        CPU_DESIRED_SIZE=${1}
      ;;
      --gpu-desired-capacity)
        shift
        GPU_DESIRED_SIZE=${1}
      ;;
      --cpu-max-capacity)
        shift
        CPU_MAX_SIZE=${1}
      ;;
      --gpu-max-capacity)
        shift
        GPU_MAX_SIZE=${1}
      ;;
      --scale-down-delay)
        shift
        SCALE_DWON_DELAY=${1}
      ;;
      --dry-run)
        DRY_MODE=true
      ;;
      --domain)
        shift
        AWS_BASED_DOMAIN=${1}
      ;;
      --keycloak-password)
        shift
        KC_PASSWORD=${1}
      ;;
      --primehub-password)
        shift
        PH_PASSWORD=${1}
      ;;
      --k8s-infra)
        K8S_INFRA_ONLY=true
      ;;
      --enforce-update-password)
        ENFORCE_UPDATE_PASSWORD=true
      ;;
      -h|--help)
        usage
        exit 0
      ;;
      --debug)
        set -x
      ;;
      *)
        if [ "${NAME}" == "" ]; then
          NAME=$1
        else
          error "[Syntax error] Should only provide one cluster name"
          usage
          exit 1
        fi
      ;;
    esac
    shift || (usage; exit 1)
  done
}

main() {
  args::parse "$@"
  node::version
  node::packages
  cdk::context "$@"
  if [ "${DRY_MODE}" == "true" ]; then
    cdk::dry
  else
    cdk::deploy
  fi
}

main "$@"
