AWSTemplateFormatVersion: "2010-09-09"
Description: PrimeHub Starter
Resources:
  PrimeHubCDKBootstrapEC2:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT1H
    Properties:
      ImageId: "ami-0b276ad63ba2d6009"
      KeyName: "rd"
      InstanceType: "t3a.micro"
      IamInstanceProfile: !Ref InstanceProfile
      UserData:
        Fn::Base64: !Sub |
              #!/bin/sh
              curl -o run-cdk.sh https://raw.githubusercontent.com/InfuseAI/primehub-aws-cdk/feature/primehub-starter/extras/ec2-user-script.sh
              chmod a+x run-cdk.sh

              # export vars
              export PRIMEHUB_MODE="${PrimeHubInstallMode}"

              ./run-cdk.sh
              /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource PrimeHubCDKBootstrapEC2

              # delete the starter stack
              aws cloudformation delete-stack --stack-name --stack ${AWS::StackName} --region ${AWS::Region}
      SecurityGroups:
      - !Ref PrimeHubCDKBootstrapEC2SecurityGroup
  AwsIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
      Path: /
      Policies:
        - PolicyName: CdkPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action:
              - cloudformation:*
              Resource: "*"
              Effect: Allow
            - Condition:
                ForAnyValue:StringEquals:
                  aws:CalledVia:
                  - cloudformation.amazonaws.com
              Action: "*"
              Resource: "*"
              Effect: Allow
            - Action: s3:*
              Resource: arn:aws:s3:::cdktoolkit-stagingbucket-*
              Effect: Allow
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref AwsIamRole
  PrimeHubCDKBootstrapEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: PrimeHub CDK Bootstrap Security Group
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Parameters:
  PrimeHubInstallMode:
    Type: String
    Default: ce
    AllowedValues:
      - ce
      - ee
    Description: PrimeHub installion mode, Please enter ce or ee. Default is ce.

